# Clippy configuration for Emulite

# Allow some lints that are too strict for this project
allow = [
    "too_many_arguments",
    "needless_pass_by_value",
    "missing_errors_doc",
    "missing_panics_doc",
    "module_name_repetitions",
    "must_use_candidate",
    "cast_possible_truncation",
    "cast_precision_loss",
    "cast_sign_loss",
]

# Deny some lints that are important for this project
deny = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

# Specific configurations
cognitive-complexity-threshold = 30
single-char-lifetime-names = false
