# Rustfmt configuration for Emulite

# Basic formatting
max_width = 100
tab_spaces = 4
newline_style = "Unix"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Functions
fn_params_layout = "Tall"
brace_style = "SameLineWhere"

# Control flow
control_brace_style = "AlwaysSameLine"
match_block_trailing_comma = true

# Comments
wrap_comments = true
comment_width = 80
normalize_comments = true

# Strings
format_strings = true
format_code_in_doc_comments = true

# Macros
format_macro_matchers = true
format_macro_bodies = true

# Other
use_field_init_shorthand = true
use_try_shorthand = true
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
